config/routes.rb
GroceApp::Application.routes.draw do
  root 'carts#index'

resources :carts

# Jozef-Woronieckis-MacBook-Pro:groce_app jozefw$ rake routes
#    Prefix Verb   URI Pattern               Controller#Action
#      root GET    /                         carts#index
#     todos GET    /todos(.:format)          todos#index
#           POST   /todos(.:format)          todos#create
#  new_todo GET    /todos/new(.:format)      todos#new
# edit_todo GET    /todos/:id/edit(.:format) todos#edit
#      todo GET    /todos/:id(.:format)      todos#show
#           PATCH  /todos/:id(.:format)      todos#update
#           PUT    /todos/:id(.:format)      todos#update
#           DELETE /todos/:id(.:format)      todos#destroy

end

app/models/cart.rb
class Cart < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def index
		@carts = Cart.all
	end


	def show
 		@cart = Cart.find(params[:id])
	end

	def new
 		 @cart = Cart.new
	end

	def create
 		@cart = Cart.create cart_params
 		redirect_to cart_path(@cart)
	end


	def edit
  		@cart = Cart.find(params[:id])
	end

	def destroy
    	Cart.find(params[:id]).destroy
    	redirect_to root_path
	end

	def update
    	@cart = Cart.find(params[:id])
    	@cart.update cart_params
    redirect_to cart_path(@cart)
	end

	private
    def cart_params
      params.require(:cart).permit(:amount, :item, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/edit.html.erb
<h1>Edit Your Grocery Item<h1>
<%= form_for @cart do |f| %>

  <%= label_tag(:amount, "Amount:") %>
  <%= f.text_field :amount %></br>

  <%= label_tag(:item, "Item:") %>
  <%= f.text_field :item %></br>

  <%= label_tag(:description, "Description") %> 
  <%= f.text_area :description %></br>

  <%= f.submit "Update" %>
<% end %>

app/views/carts/index.html.erb
<h1> Grocery Index Page! </h1>

<%= link_to "New Grocery Item", new_cart_path %><br></br>

<% @carts.each do |cart| %>
    <li>
      <%= link_to cart.item, cart_path(cart.id) %>
      <%= link_to "edit", edit_cart_path(cart[:id]) %>
      <%= link_to "delete", cart, method: :delete, data: { confirm: "You sure?" }%>
    </li>
<% end %>

app/views/carts/new.html.erb
<h1>Create a New Grocery Item</h1>
<%= form_for @cart do |f| %>

  <%= label_tag(:amount, "Amount:") %>
  <%= f.text_field :amount %></br>

  <%= label_tag(:item, "Item:") %>
  <%= f.text_field :item %></br>

  <%= label_tag(:description, "Description") %> 
  <%= f.text_area :description %></br>
  <%= f.submit "Create" %>
<% end %>

app/views/carts/show.html.erb
<h1>Grocery Cart Show Page</h1>
<p>Amount: <%= @cart['amount']%></p>
<p>Item: <%= @cart['item']%></p>
<p>Description: <%= @cart['description']%></p>

<%= link_to "Back To Grocery List",carts_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GroceApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>